services:
  - type: web
    name: composite-behavioral-modeling
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn composite_behavioral_modeling.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        value: "eanw-bm$p=ek8t3q5+e)5$)%ir%)1xn&16$grpy%jqqh^vt@l)"
