services:
  - type: web
    name: composite-behavioral-modeling
    env: python
    plan: free
    # We add "cd composite_behavioral_modeling &&" to the build command
    buildCommand: pip install -r requirements.txt && cd composite_behavioral_modeling && python manage.py migrate && python manage.py collectstatic --noinput && cp -r staticfiles ../
    # We tell gunicorn where the python files are
    startCommand: gunicorn --pythonpath composite_behavioral_modeling composite_behavioral_modeling.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        value: "eanw-bm$p=ek8t3q5+e)5$)%ir%)1xn&16$grpy%jqqh^vt@l)"
