# Generated by Django 3.2 on 2026-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='identity_theft_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Id', models.CharField(max_length=300)),
                ('Trans_Id', models.CharField(max_length=300)),
                ('Age', models.CharField(max_length=300)),
                ('Followers', models.CharField(max_length=300)),
                ('NAME_CONTRACT_TYPE', models.CharField(max_length=300)),
                ('GENDER', models.CharField(max_length=300)),
                ('AMT_INCOME_TOTAL', models.CharField(max_length=300)),
                ('AMT_CREDIT', models.CharField(max_length=300)),
                ('AMT_ANNUITY', models.CharField(max_length=300)),
                ('AMT_GOODS_PRICE', models.CharField(max_length=300)),
                ('NAME_INCOME_TYPE', models.CharField(max_length=300)),
                ('NAME_FAMILY_STATUS', models.CharField(max_length=300)),
                ('Prediction', models.CharField(max_length=300)),
            ],
        ),
    ]
